# Step 1: Build the Angular app
FROM node AS build

WORKDIR /app

# Copy package files and install dependencies
COPY hl-angular . 
RUN npm install -g @angular/cli

# Build the Angular app
RUN ng build --configuration production

# Step 2: Serve the app with Nginx
FROM nginx:stable-alpine

# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d

# Copy built Angular app from previous stage
COPY --from=build /app/dist/hl-angular /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
