services:
  #Backend 
  backend:
    build:
      context: ./backend
    # restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - DEBUG=${APP_DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    networks:
      - hardcorelifting
    
  mockserver:
    build:
      context: ./mock-server
    ports:
      - '3001:3001'
    networks:
      - hardcorelifting

  # Frontend 
  frontend:
    container_name: frontend_hcl_app
    build:
      context: ./frontend
    restart: unless-stopped
#    volumes:
      #- ./frontend:/app
      #- /app/node_modules
    ports:
      - '80:4200'
    networks:
      - hardcorelifting
    depends_on:
      - backend

  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hardcorelifting
      
volumes:
  db_data:
  ollama-data:

networks:
  hardcorelifting:
    driver: bridge
