services:
  # Backend 
  backend:
    container_name: backend_hcl_app
    image: backend_hcl_image
    build:
      context: ./backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
    ports:
      - '127.0.0.1:5000:5000'
    environment:
      - DEBUG=${APP_DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    networks:
      - hardcorelifting

  # Frontend 
  frontend:
    container_name: frontend_hcl_app
    image: frontend_hcl_image
    build:
      context: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5005/api
    networks:
      - hardcorelifting

  # Base de datos PostgreSQL
  db:
    container_name: db_comidamind_app
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hardcorelifting
      
volumes:
  db_data:
  ollama-data:

networks:
  hardcorelifting:
    driver: bridge
