services:

  mockserver:
    build:
      context: ./mock-server
    ports:
      - '3001:3001'

  frontend:
    container_name: frontend_hcl_app
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - mockserver

      
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - mimir
      - loki
      - tempo

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki

  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo/local-config.yaml
    ports:
      - "3200:3200"
    volumes:
      - tempo-data:/var/tempo

  mimir:
    image: grafana/mimir:latest
    command: -config.file=/etc/mimir/mimir.yml
    ports:
      - "9009:9009"
    volumes:
      - mimir-data:/mimir
      - ./IaC/mimir-config.yaml:/etc/mimir/mimir.yml

  prometheus: 
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./IaC/prometheus.yml:/etc/prometheus/prometheus.yml

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command:
      - -nginx.scrape-uri=http://hardcorelifting.fit/nginx_status
    ports:
      - "9113:9113"
    depends_on:
      - frontend
  

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: "host"   # so it binds directly to VM’s 9100
    pid: "host"            # lets it see host processes
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
    ports:
      - "9100:9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"   # Web UI and metrics
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped


volumes:
  db_data:
  grafana-data:
  loki-data:
  tempo-data:
  mimir-data: