server:
  http_listen_port: 9009

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/mimir/compactor

limits:
  ingestion_rate: 50000
  ingestion_burst_size: 100000
