global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['mockserver:3001']  # Replace with your service name & port
  
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']


remote_write:
  - url: http://mimir:9009/api/v1/push